### ISSUE TITLE
FIX: Buffer state after garbled message

### ISSUE THREAD

**Issue by divaykin** [libtrading/libtrading#104]
As far as I understand if we detect "garbled" message parsing stops and buffer effectively becomes unusable? If there is one more message in there which is not garbled would be be parsed?

**Comment by divaykin** [comment]
Actually not, it seems like it'd retry indefinitely until next message would be found (begin string). But garbled content would stay in the buffer?

**Comment by divaykin** [comment]
Or this line would remove all garbled content eventually? https://github.com/libtrading/libtrading/blob/master/lib/proto/fix_message.c#L476

**Comment by mstanichenko** [comment]
```C
fail:
   if (ret != FIX_MSG_STATE_PARTIAL)
      goto retry;

   buffer_advance(buffer, start - buffer_start(buffer));
```

If  ```ret == FIX_MSG_STATE_PARTIAL```  i.e. buffer contains partial data but not garbled, we preserve buffer's start pointer so that it is returned intact. Next time we call ```fix_message_parse``` we will parse it from the very beginning. Otherwise, we ```goto retry``` i.e. skip the data which we assume garbled and try to decode a message from the point which we failed last time.

**Comment by divaykin** [comment]
I hope there is no case of having an infinite loop due to tricky garbled case when buffer not advancing on a field boundary.

**Comment by mstanichenko** [comment]
Denis, I should admit that this is a reasonable question, indeed. The idea was that ```buffer_size(buffer)``` at line ```449``` is strictly less than ```buffer_size(buffer)``` at line ```474```. If it is not the case, that must be a BUG. If you feel like getting into this, please let me know and I will look at it closer.

**Comment by divaykin** [comment]
I've no test / failure case for this @mstanichenko so lets leave it. Thanks for explaining, was very helpful
