### ISSUE TITLE
FIX: partial send to non blocking sockets

### ISSUE THREAD

**Issue by divaykin** [libtrading/libtrading#114]
https://github.com/libtrading/libtrading/blob/01547375ee4299a089a9b5b2e0d00315d5da97c7/lib/proto/fix_message.c#L700

number of bytes sent is lost right? if the send buffer is almost full the there could be partial message transmission.

currently there is no way of detecting so. we need to return number of bytes sent.

how about returning number of bytes from this function? @penberg @mstanichenko

**Comment by divaykin** [comment]
how about the following implementation of `sys_sendmsg`

```c
ssize_t sys_sendmsg(int fd, struct iovec *iov, size_t length, int flags) 
{
	struct msghdr msg = (struct msghdr) {
		.msg_iov	= iov,
		.msg_iovlen	= length,
	};	
	ssize_t iov_byte_len;
	ssize_t len;
	ssize_t i;
	
	do {
		len = sendmsg(fd, &msg, flags);
		if (len <= 0) return len;

		iov_byte_len = 0;

		for (i = 0; i < msg.msg_iovlen; ++i) {
			iov_byte_len += msg.msg_iov[i].iov_len;
		}
	} while (len < iov_byte_len);
}
```

**Comment by penberg** [comment]
@divaykin That looks OK to me. We can still send a partial message and bail out because the kernel returned ``EAGAIN``, for example, to avoid blocking. But that's then propagated as an error to the caller which needs to either terminate the session or re-resend the message. The partial message is detected as "garbled" by the other end so that should be fine.

**Comment by penberg** [comment]
@mstanichenko ping?

**Comment by mstanichenko** [comment]
Hi guys, sorry for a delay.

a) I didn't get an idea of  ```sys_sendmsg()``` above. Why do we need ```iov_byte_len``` at all? And why do we evaluate ``iov_byte_len`` at every loop iteration? Its value seems to be constant. I must be missing something here. Could you please help me with it?

b) Assume that we make ```fix_message_send()``` return the number of bytes transferred. That means that ```fix_session_send()``` returns the number of bytes as well. How a user should interpret the return value? Which one is to be considered as an error and which one is to be considered as a success? AFAICT, a user has no idea how many bytes a message will  take in a byte stream. Can I have an example of a simple use-case? How it is supposed to work? I can suggest returning the number of bytes that **are not sent** if we really need to operate with number of bytes.

c) Out of curiosity, what would we like to support here? Would we like to send a message with no guarantees via non-blocking socket?

**Comment by divaykin** [comment]
Hi @mstanichenko 

a) `iov_base` and `iov_len` are updated by the kernel according to whatever has been actually sent. http://cyberkinetica.homeunix.net/os2tk45/tcppr/200_L2_sendmsg.html

> TCP/IP alters iov_base and iov_len for each element in the input struct iovec array. iov_base will point to the next character of the processed (sent or received) data on the original buffer, and iov_len will become (input value - processed length). Thus if only partial data has been sent or received and the application expects more data to send or receive, it can pass the same iovec structure back in a subsequent call.

for example see this code in kernel https://github.com/torvalds/linux/blob/de182468d1bb726198abaab315820542425270b7/fs/cifs/transport.c#L221

b) yes we can return bytes `not sent`. it's difficult to say what should be a meaningful action by the user. typically it's better to not send a message at all then send it late. i'd simply consider transmit attempt as failed. to meaningfully retry later we need to save iov vector (which you did for logging purposes)

c) yes exactly. i believe the worst is to block and wait while socket buffer would be transmitted, better just not send it at all in most cases.

there might be other cases of partial message send such as unexpected connection drop or whatever.

in practice it happens rarely indeed

**Comment by mstanichenko** [comment]
Hi @divaykin,

a) The documentation you refer to is not about Linux at all but OS/2.
[Posix standard](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sendmsg.html) does not say anything about it. Moreover, I believe [Linux] (http://linux.die.net/man/2/sendmsg) does not modify it either. Are you running things on OS/2?

b) My point was to return a value which a user can interpret. What can one say if ```fix_session_send()``` returns ```42```? Is it an error or not?

c) All you want to know whether your message was sent completely or not. That's it. Why would you want to resend things again and again in ```sys_sendmsg()```? Increasing the number of attempts to send a message will not provide you any guarantees at all. This is just not efficient and kills performance. Just think what happens inside ```sys_sendmsg``` above.

So, I am fine to return a value which tells a user if the whole message was sent or just a part of it. But I do not accept you implementation of ```sys_sendmsg```. It makes things less efficient but does not provide guarantees either. Think of it. What are the chances that ``sendmsg`` returns ```EAGAIN``` or ``EWOULDBLOCK`` you call it second time if it is not able to send a message completely the first time? I consider them high. So, I don't see much sense to call ```sendmsg``` second time. We should just return a value to a user which tells that a message is partially sent. That is already a good indication that send buffer is full. A user can decide what to do futher.

**Comment by divaykin** [comment]
@mstanichenko 

a) you're right, `iov` is not modified so we may need to change `iov` ourselves.

b) sure, it's somewhat more difficult to change `iov` for retry knowing only unsent length but it can be computed from `iov` though.

c) it does not indeed. one more attempt (getting `EAGAIN`) should not hurt though. we can skip this part, it's not essential.

d) to do meaningful retry attempt user would need to change the `iov` according to what has been sent. or we can adjust `iov` in case of partial send for the user.

**Comment by mstanichenko** [comment]
@divaykin,

> one more attempt (getting EAGAIN) should not hurt though

It actually does. Again, think what happens if you are not able to send a message completely the first time goes the second iteration. ```sendmsg``` returns ```EAGAIN``` or  ``EWOULDBLOCK`` which you propagate to a user. A user gets a negative value without knowing a part of its message is already sent behind his back!

I suggest merging this commit as a solution to initial issue reported
 https://github.com/mstanichenko/libtrading/commit/10a3b2beb4c66b20faa8861ece517bdd9f7b4a01

**Comment by divaykin** [comment]
@mstanichenko it should be sufficient because you store `iov` in your `struct fix_message` so user can adjust `iov` and then try to send it again if he feels like. maybe it worth doing a helper function but it's not immediately needed.

**Comment by divaykin** [comment]
@mstanichenko could you please open the pull request? i'll do the similar thing for templates

**Comment by mstanichenko** [comment]
Sure Denis. Will do.

**Comment by mstanichenko** [comment]
#115

**Comment by divaykin** [comment]
i think we're all set now
