### ISSUE TITLE
NASDAQ TotalView-ITCH 5.0 support

### ISSUE THREAD

**Issue by penberg** [libtrading/libtrading#39]
NASDAQ has a new ITCH version.

Specification:

http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHSpecification.pdf

Example file:

ftp://emi.nasdaq.com/ITCH/Beta%20Files/

**Comment by jvirtanen** [comment]
The FTP server on NASDAQ's end seems to have pretty short connection timeouts. I managed to download the larger files in multiple batches with `curl` using the `--continue-at` option. For example:

    curl --continue-at - --remote-name ftp://emi.nasdaq.com/ITCH/10022014.NASDAQ_ITCH50.gz

**Comment by theojepsen** [comment]
@penberg 
ITCH 5.0 support was added by this PR:
https://github.com/libtrading/libtrading/pull/139

I think this issue can be closed.
