### ISSUE TITLE
Use EXIT_FAILURE in libtrading-config.c for clarity?

### ISSUE THREAD

**Issue by tfarina** [libtrading/libtrading#81]
Maybe we could use EXIT_FAILURE in https://github.com/libtrading/libtrading/blob/master/libtrading-config.c#L22

**Comment by penberg** [comment]
I don't see why not and ``EXIT_SUCCESS`` as well. Would you be interested in sending a pull request and perhaps cleaning up the other files as well for this?

**Comment by tfarina** [comment]
Sure, I will try to send you a pull request on the weekend.

**Comment by penberg** [comment]
@tfarina Awesome!

**Comment by tfarina** [comment]
Please, give me a few more days to work on this. This weekend was impossible.
