### ISSUE TITLE
only argv[1] used in tape.c:32

### ISSUE THREAD

**Issue by tfarina** [libtrading/libtrading#82]
Instead of passing argc and argv to parse_builtin_cmd() in [1], we could just pass argv[1] as cmd_name.

https://github.com/libtrading/libtrading/blob/master/tools/tape/tape.c#L32

**Comment by penberg** [comment]
@tfarina Sure, we can do that.

**Comment by tfarina** [comment]
I will try to work on that next weekend. I need to learn more about pull-request to handle it better.

**Comment by tfarina** [comment]
Sorry for the delay. I'm looking into this now.

**Comment by tfarina** [comment]
Done. PTAL.
