### ISSUE TITLE
FIX: send/recv/parse/unparse flags

### ISSUE THREAD

**Issue by mstanichenko** [libtrading/libtrading#83]
I can see at least four potential groups of flags: fix_send_flag, fix_recv_flag, fix_parse_flag, fix_unparse_flag. Are we going to maintain any relationship between them? Or they should be completely independent? Can't we join (fix_recv_flag and fix_parse_flag) and (fix_send_flag and fix_unparse_flag). At the moment it is impossible to call fix_session_recv() with FIX_PARSE_NO_CSUM

**Comment by penberg** [comment]
There's no relationship between RX and TX flags that those ought to be separate. However, parsing flags are probably a subset of RX flags and unparsing flags are a subset of TX flags. So it perhaps makes sense to try to preserve that structure in types.

**Comment by divaykin** [comment]
done

**Comment by mstanichenko** [comment]
Fixed with #87
