### ISSUE TITLE
FIX: extra flags to fix_session_recv

### ISSUE THREAD

**Issue by divaykin** [libtrading/libtrading#84]
https://github.com/libtrading/libtrading/blob/master/lib/proto/fix_session.c#L183

`_recv` accepts flags mostly used to do non-blocking read (MSG_DONTWAIT). in addition to `recv(2)` specific flags I'd like to add another flags to pass to `fix_message_parse` function (i.e. NO_CHECKSUM).

should I add two set of flags (`flag_recv`, `flag_parse`) or there is a better way (64 bit)?

**Comment by mstanichenko** [comment]
Related issue #83

**Comment by mstanichenko** [comment]
I agree with Pekka

> There's no relationship between RX and TX flags that those ought to be separate. However, parsing flags are probably a subset of RX flags and unparsing flags are a subset of TX flags. So it perhaps makes sense to try to preserve that structure in types.

**Comment by divaykin** [comment]
Cool, I'll make `fix_recv_flag` and `fix_parse_flag` flags then, thanks

**Comment by mstanichenko** [comment]
Will you make sure that fix_parse_flag is a subset of fix_recv_flag?

**Comment by divaykin** [comment]
I thought of just passing two separate parameters. `fix_recv_flags` are `recv(2)` specific bit mask OS dependant

**Comment by mstanichenko** [comment]
Will it be possible to call fix_session_recv() with FIX_PARSE_NO_CSUM? If yes, then how?

**Comment by divaykin** [comment]
`fix_session_recv(session, &msg, MSG_DONTWAIT, FIX_PARSE_NO_CSUM);`

`fix_recv_flags = MSG_DONTWAIT` `fix_parse_flags = FIX_PARSE_NO_CSUM`

**Comment by mstanichenko** [comment]
Then you somehow disagree with initial statement that
> parsing flags are probably a subset of RX flag

**Comment by divaykin** [comment]
ah, yes indeed I do because of the following flags could be put into RX flags: http://lxr.free-electrons.com/source/include/linux/socket.h#L250 and there is simply little room for parse flags unless we make these 64 bits

**Comment by mstanichenko** [comment]
How many 'parse flags' do you expect?

IMHO, it is a little bit misleading to pass flags to one function (```fix_message_parse```) by calling another (```fix_session_recv```) with parameter which it doesn't use. Essentially there are two flags consumers in ```fix_session_recv``` i.e. ```buffer_recv``` and ```fix_message_parse```. What if there are more? Will we have to introduce another set?

Do you think we can somehow have a single set which we could effectively map to ```buffer_recv```- flags and  ```fix_message_parse``` - flags internally? Or you believe it is not worth doing?

**Comment by divaykin** [comment]
personally I don't need to pass OS level flags like `MSG_DONTWAIT` because my socket is already in non-blocking mode. I just see it's done all over the `libtrading` codebase.

what we can do to improve is - only allow `libtrading` specific flags but not OS `recv(2)` flags in there. i.e. do a translation of `libtrading` to `recv(2)` internally (very simple, support just `MSG_DONTWAIT`). then we would be able to pack everything into one set of flags.

I don't mind doing so, no strong view one way or another.

**Comment by divaykin** [comment]
done
