### ISSUE TITLE
FIX: template support

### ISSUE THREAD

**Issue by divaykin** [libtrading/libtrading#86]
Note - zero padding is allowed by FIX standard for both Int and Float see http://fixwiki.org/fixwiki/FloatDataType and http://fixwiki.org/fixwiki/IntDataType even though there might be standard incompatible exchanges but then again we can't really support wildly non FIX protocol compatible counterparts.

I'd like to propose the following design:
- introduce `buffer *const_body` in the message which would be untouched by `unparse`
- create another files `fix_template.c` and `fix_template.h` which would hold all the new code
- will add `nr_const_fields` to `fix_message`
- function `fix_template_prepare(fix_message *self)` doing the following (+random notes)
  - serialize `BeginString`
  - serialize zero padded (4 digits, set in #define) `BodyLength`, it'd be always on fixed offset so we can replace it easily later
  - there would be no need for `head_buf` because head length would be fixed. I'll set it to `NULL` and in `send` code would not include any `NULL` buffers into `io_vec` therefore if `head_buf` or `const_buf` are `NULL` it won't be sent.
  - it would format `MsgType` to `const_buf` (user has to append all he's const fields afterwards to `const_buf`)
  - `const_buf` would be placed before `body_buf` in the message (in general)
  - it'd serialize `nr_const_fields` first fields into `const_buf` after `MsgType`
  - all other fields - `SenderCompID`, etc would not be serialized unless provided in `nr_const_fields`
- function `fix_template_unparse(fix_message *self)` which would do the following
  - it'd update zero padded `MsgSeqNum`
  - will serialize all fields from `nr_const_fields` to `nr_fields` (non const) to `body_buf`
  - compute checksum & append it to `body_buf`
- function `fix_fields_unparse(struct fix_field fields[], int nr_start, int nr_end, buffer *buf)` which would help to serialize part of `fields` to `const_buf`

How about that? @penberg @mstanichenko

**Comment by penberg** [comment]
Fixed by commit 717e0961d34c47cbf7d04a97bfbd0b05174694a4.
